#!/usr/bin/env bash
# worktree.sh — Create and manage git worktrees for parallel pipeline work
#
# Usage:
#   ./.claude/scripts/worktree.sh create <pipeline>
#   ./.claude/scripts/worktree.sh remove <pipeline>
#   ./.claude/scripts/worktree.sh list [pipeline]

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ALLOC="${ROOT}/.claude/scripts/alloc-ports.sh"

cmd_create() {
  local pipeline="$1"
  local branch="pipeline/${pipeline}"
  local worktree_dir="${ROOT}/.worktrees/${pipeline}"

  if [ -d "$worktree_dir" ]; then
    echo "Worktree already exists: $worktree_dir"
    "$ALLOC" alloc "$pipeline"
    exit 0
  fi

  if ! git rev-parse --verify "$branch" >/dev/null 2>&1; then
    git branch "$branch" main
  fi

  git worktree add "$worktree_dir" "$branch"

  # Allocate unique ports
  local ports
  ports=$("$ALLOC" alloc "$pipeline")

  local mcp_port
  mcp_port=$(echo "$ports" | grep MCP_PORT | cut -d= -f2)

  # Write .env.ports into worktree root
  cat > "${worktree_dir}/.env.ports" <<ENVEOF
# Auto-generated by worktree.sh — unique ports for pipeline: ${pipeline}
MCP_PORT=${mcp_port}
ENVEOF

  echo "Worktree ready: $worktree_dir"
  echo "Branch: $branch"
  echo "MCP_PORT=${mcp_port}"
}

cmd_remove() {
  local pipeline="$1"
  local branch="pipeline/${pipeline}"
  local worktree_dir="${ROOT}/.worktrees/${pipeline}"

  if [ -d "$worktree_dir" ]; then
    git worktree remove "$worktree_dir" --force 2>/dev/null || true
    echo "Worktree removed: $worktree_dir"
  else
    echo "No worktree found: $worktree_dir"
  fi

  git branch -d "$branch" 2>/dev/null || true

  "$ALLOC" free "$pipeline"

  echo "Pipeline cleaned up: $pipeline"
}

cmd_list() {
  local pipeline="${1:-}"

  if [ -n "$pipeline" ]; then
    local worktree_dir="${ROOT}/.worktrees/${pipeline}"
    if [ ! -d "$worktree_dir" ]; then
      echo "No worktree for pipeline: $pipeline"
      return 0
    fi
    echo "=== Pipeline: $pipeline ==="
    echo "  Branch: pipeline/$pipeline"
    echo "  Path: $worktree_dir"
    if [ -f "$worktree_dir/.env.ports" ]; then
      echo "  Ports:"
      grep -E '^MCP_PORT=' "$worktree_dir/.env.ports" | sed 's/^/    /'
    fi
  else
    echo "=== Active Pipelines ==="
    for d in "${ROOT}/.worktrees"/*/; do
      local name
      name="$(basename "$d")"
      [[ "$name" == .* ]] && continue
      [ -d "$d" ] || continue
      echo "  $name/ -> pipeline/$name"
    done
  fi

  echo ""
  echo "=== Port Allocations ==="
  "$ALLOC" list
}

case "${1:-help}" in
  create)  cmd_create "${2:?pipeline required}" ;;
  remove)  cmd_remove "${2:?pipeline required}" ;;
  list)    cmd_list   "${2:-}" ;;
  *)
    echo "Usage: $0 {create|remove|list} <pipeline>"
    exit 1
    ;;
esac
