name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cargo-dist:
    name: cargo-dist
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: axodotdev/cargo-dist@v0.29.0
        with:
          command: build
